Hw02 unpack string
selestica/home_work pull request #2
Opened 2020-03-17 07:29 UTC by selestica

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-03-18 07:38 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/37867/6026/

Здравствуйте!

Спасибо за работу. Давайте разберемся с парой комментариев ниже и продолжим после.

У вас достаточно многословный стиль программирования, что непривычно для Go (да и необязательно для Go). И это не всегда упрощает чтение кода, а порою и затрудняет его. Но это мое субъективное мнение, например
```golang
defaultString -> input
defaultChar -> ch
numberOfRepeats -> repeatsCount
previousCharIsDigit -> prevIsDigit
etc
```

2020-03-18 07:38 UTC, Antonboom commented on hw01_hello_now/main.go
> +	localTime, err := ntp.Time("ntp1.stratum2.ru")
Что-то я не могу понять, как сюда попало ДЗ №1, если оно уже вмержено?

2020-03-18 07:38 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			input: "1d$2d",
Это невалидная строка, так как для единицы нет символа

2020-03-18 07:38 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	var previousCharIsDigit bool = false
Достаточно 
```
var previousCharIsDigit bool
```

2020-03-18 07:38 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	repeatedChar := ""
Предпочтительнее 
```
var repeatedChar string
```

2020-03-18 07:38 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			input: "д2а0",
Еще бы пару негативных и позитивных тестиков :(

2020-03-18 08:54 UTC, selestica commented on hw01_hello_now/main.go
> +	localTime, err := ntp.Time("ntp1.stratum2.ru")
Сам не понял почему в этот pr попали коммиты по ДЗ №1. А ДЗ №1 я смержил после пуша ДЗ №2 в этот pr.

2020-03-18 09:25 UTC, selestica commented on hw02_unpack_string/unpack_test.go
> +			input: "д2а0",
Тестировщик внутри меня тоже недоволен. Добавлю еще тестов.

2020-03-19 07:09 UTC, Antonboom approved these changes
Принято
10 / 10

2020-03-19 07:09 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +// Unpack formats the string according to the given format: "a4bc2d5e" => "aaaabccddddde"
Лайк за комментарий к экспортируемой функции

2020-03-19 07:09 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	input += "\n" // to successfully iterate over last char in "for" loop
Не понял, почему не работает без этого, но да ладно

Тогда уж выполнять после if ниже

2020-03-19 07:09 UTC, Antonboom commented on hw01_hello_now/go.mod
> +go 1.14
Обычно в начале файла, но as u wish

2020-04-05 16:31 UTC, merged